-- PDF Quiz Generator — PostgreSQL Schema
-- Auto-generated by SQLAlchemy via db.create_all()

CREATE TABLE source_documents (
    id          VARCHAR(36)  PRIMARY KEY,
    filename    VARCHAR(512) NOT NULL,
    title       VARCHAR(512),
    file_path   VARCHAR(1024),
    page_count  INTEGER,
    status      VARCHAR(32)  DEFAULT 'pending',  -- pending|processing|ready|error
    error_msg   TEXT,
    created_at  TIMESTAMP    DEFAULT NOW()
);

CREATE TABLE content_chunks (
    id          VARCHAR(36)  PRIMARY KEY,
    document_id VARCHAR(36)  NOT NULL REFERENCES source_documents(id) ON DELETE CASCADE,
    chunk_index INTEGER      NOT NULL,
    text        TEXT         NOT NULL,
    page_start  INTEGER,
    page_end    INTEGER,
    token_count INTEGER,
    grade       INTEGER,                  -- e.g. 1, 3, 4
    subject     VARCHAR(128),             -- e.g. "Math", "Science", "English"
    topic       VARCHAR(256),             -- e.g. "Shapes", "Plants", "Grammar"
    created_at  TIMESTAMP    DEFAULT NOW()
);

CREATE TABLE quiz_questions (
    id             VARCHAR(36)  PRIMARY KEY,
    document_id    VARCHAR(36)  NOT NULL REFERENCES source_documents(id) ON DELETE CASCADE,
    chunk_id       VARCHAR(36)  REFERENCES content_chunks(id),
    question_text  TEXT         NOT NULL,
    question_type  VARCHAR(32)  DEFAULT 'mcq',  -- mcq | true_false | fill_in_the_blank
    options        JSONB,                        -- null for fill_in_the_blank
    correct_answer TEXT         NOT NULL,
    explanation    TEXT,
    difficulty     INTEGER      DEFAULT 3,       -- 1 (easy) to 5 (hard)
    topic_tags     JSONB        DEFAULT '[]',
    times_shown    INTEGER      DEFAULT 0,
    times_correct  INTEGER      DEFAULT 0,
    created_at     TIMESTAMP    DEFAULT NOW()
);

CREATE TABLE quiz_sessions (
    id                 VARCHAR(36)  PRIMARY KEY,
    document_id        VARCHAR(36)  NOT NULL REFERENCES source_documents(id),
    user_id            VARCHAR(256) DEFAULT 'anonymous',
    current_difficulty INTEGER      DEFAULT 3,
    questions_asked    INTEGER      DEFAULT 0,
    questions_correct  INTEGER      DEFAULT 0,
    status             VARCHAR(32)  DEFAULT 'active',  -- active | completed
    created_at         TIMESTAMP    DEFAULT NOW(),
    updated_at         TIMESTAMP    DEFAULT NOW()
);

CREATE TABLE session_answers (
    id                 VARCHAR(36)  PRIMARY KEY,
    session_id         VARCHAR(36)  NOT NULL REFERENCES quiz_sessions(id) ON DELETE CASCADE,
    question_id        VARCHAR(36)  NOT NULL REFERENCES quiz_questions(id),
    user_answer        TEXT,
    is_correct         BOOLEAN,
    time_taken_ms      INTEGER,
    difficulty_at_time INTEGER,
    answered_at        TIMESTAMP    DEFAULT NOW()
);

-- Useful indexes
CREATE INDEX idx_chunks_document    ON content_chunks(document_id);
CREATE INDEX idx_chunks_subject     ON content_chunks(subject);
CREATE INDEX idx_chunks_topic       ON content_chunks(topic);
CREATE INDEX idx_questions_document ON quiz_questions(document_id);
CREATE INDEX idx_questions_diff     ON quiz_questions(difficulty);
CREATE INDEX idx_questions_type     ON quiz_questions(question_type);
CREATE INDEX idx_answers_session    ON session_answers(session_id);
